services:
  mysql:
    image: mysql:8.0
    container_name: healthcare-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: healthcare
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: healthcare-backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: 1234
    ports:
      - "8081:8080"

volumes:
  mysql_data: